### ISSUE TITLE
Proxy settings causes CR to fail

### ISSUE THREAD

**Issue by hlawatschek** [theforeman/foreman_fog_proxmox#149]
When I add proxy settings to foreman I get the following error configuring the compute resource:

ERF42-9354 [Foreman::Exception]: Failed retrieving proxmox identity client caused by :disable_proxy parameter and :proxy parameter cannot both be set at the same time.

**To Reproduce**
+ Add a proxy setting to Settings/General/HTTP(S) proxy
+ try to configure the proxmox compute resource

**Expected behavior**
The compute resource can be configured

**Screenshots**
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1412316/82052164-7b4e4800-96bb-11ea-8eb4-4398dadfea18.png">

**Comment by tristanrobert** [comment]
If you need to add a proxy setting, you must uncheck `disable proxy` checkbox.

**Comment by hlawatschek** [comment]
Where can I find the checkbox?
<img width="707" alt="Screenshot 2020-05-15 at 03 15 32 PM" src="https://user-images.githubusercontent.com/1412316/82054402-2f050700-96bf-11ea-91a1-6eebd02e3879.png">

**Comment by tristanrobert** [comment]
You can configure one global http_proxy in adminster > settings: https://theforeman.org/manuals/2.0/index.html#5.9HTTP(S)Proxy
It is now not possible to set a different proxy from global to proxmox compute resource. Maybe it could be a new enhancement!

**Comment by hlawatschek** [comment]
maybe the production.log entry will help a bit:

```
2020-05-15T14:51:08 [E|app|8a1e04f2] <ArgumentError> `:disable_proxy` parameter and `:proxy` parameter cannot both be set at the same time.
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon/connection.rb:429:in `setup_proxy'
        /usr/share/foreman/lib/foreman/http_proxy/excon_connection_extension.rb:8:in `request'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:96:in `request_credentials'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:80:in `get_credentials'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:52:in `authenticate'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox/core.rb:118:in `authenticate'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/identity/proxmox.rb:109:in `initialize'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/service.rb:115:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/service.rb:115:in `new'
```

**Comment by tristanrobert** [comment]
I have found an easy fix. I will release it in 0.11.1

**Comment by hlawatschek** [comment]
Cool! looking forward to testing this :-)

**Comment by hlawatschek** [comment]
Hi @tristanrobert,
after applying the patch I receive the following error:
`ERF42-5722 [Foreman::Exception]: Failed retrieving proxmox identity client caused by premature end of char-class: /(^|\.)[$/`

here's the production.log entry:
```
2020-05-18T09:50:30 [E|app|050aa915] <RegexpError> premature end of char-class: /(^|\.)[$/
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon/connection.rb:439:in `block in setup_proxy'
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon/connection.rb:439:in `index'
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon/connection.rb:439:in `setup_proxy'
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon/connection.rb:63:in `initialize'
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon.rb:131:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/excon-0.58.0/lib/excon.rb:131:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/connection.rb:59:in `initialize'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:91:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:91:in `request_credentials'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:80:in `get_credentials'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox.rb:52:in `authenticate'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/proxmox/core.rb:118:in `authenticate'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.11.1/lib/fog/identity/proxmox.rb:109:in `initialize'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/service.rb:115:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/fog-core-2.1.0/lib/fog/core/service.rb:115:in `new'
        /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.10.2/app/models/foreman_fog_proxmox/proxmox.rb:116:in `identity_client'
        /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.10.2/app/models/foreman_fog_proxmox/proxmox_version.rb:32:in `version'
        /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.10.2/app/models/foreman_fog_proxmox/proxmox_version.rb:25:in `version_suitable?'
        /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.10.2/app/models/foreman_fog_proxmox/proxmox_connection.rb:49:in `test_connection'
        /usr/share/foreman/app/controllers/compute_resources_controller.rb:134:in `test_connection'
```

**Comment by tristanrobert** [comment]
1. You should try last release: 0.11.1
2. Your error seems related to your no_proxy hosts list: https://github.com/excon/excon/blob/f932cdb0dd074e95140dc4c1ab5fd7b3c61d4ef9/lib/excon/connection.rb#L439

**Comment by hlawatschek** [comment]
Thanks for the hint. It was a configuration error.

**Comment by hlawatschek** [comment]
Or a bug in the excon library ;-)
