### ISSUE TITLE
Error trying to view compute resources

### ISSUE THREAD

**Issue by keslerm** [theforeman/foreman_fog_proxmox#203]
**Describe the bug**
On a totally fresh install of Foreman and the Proxmox plugin, after adding the Proxmox Compute resources, trying to click on any of the VMs presents an error.

**To Reproduce**
1. Install foreman and the proxmox plugin via apt
2. Add a compute resource for the Proxmox node
3. Click on the Virtual Machines tab within the compute resource
4. Click on any of the VMs listed
5. See error

**Expected behavior**
To not have an error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser NA
 - Version 20.04
 - Promox version is 6.4-8
 - Also tested Proxmox version 6.3-3

**Additional context**

Stack trace
```
2021-06-17T17:55:40 [I|app|30ae0d9c] Started GET "/compute_resources/1-test/vms/400" for 172.16.10.10 at 2021-06-17 17:55:40 +0000
2021-06-17T17:55:40 [I|app|30ae0d9c] Processing by ComputeResourcesVmsController#show as HTML
2021-06-17T17:55:40 [I|app|30ae0d9c]   Parameters: {"compute_resource_id"=>"1-aegiszero", "id"=>"400"}
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendering compute_resources_vms/show.html.erb within layouts/application
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendered compute_resources_vms/show.html.erb within layouts/application (Duration: 6.9ms | Allocations: 1192)
2021-06-17T17:55:40 [W|app|30ae0d9c] undefined method `name' for nil:NilClass
2021-06-17T17:55:40 [I|app|30ae0d9c] Backtrace for 'undefined method `name' for nil:NilClass' error (ActionView::Template::Error): undefined method `name' for nil:NilClass
 30ae0d9c | /usr/share/foreman/app/views/compute_resources_vms/show.html.erb:17:in `_810087a3a73583dcc7377310e5e2046c'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/base.rb:274:in `_run'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/template.rb:185:in `block in render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:182:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/template.rb:385:in `instrument_render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/template.rb:183:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:43:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/template_renderer.rb:13:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:117:in `block in _render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/base.rb:304:in `in_rendering_context'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:116:in `_render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/streaming.rb:218:in `_render_template'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:103:in `render_to_body'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/rendering.rb:25:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:36:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
 30ae0d9c | /usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/core_ext/benchmark.rb:14:in `ms'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:43:in `render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-4.10.0/lib/audited/sweeper.rb:14:in `around'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-dsl-2.4.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.18/lib/apipie/static_dispatcher.rb:66:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.18/lib/apipie/extractor/recorder.rb:137:in `call'
 30ae0d9c | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.5.18/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 30ae0d9c | /usr/share/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 30ae0d9c | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 30ae0d9c | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/secure_headers-6.3.2/lib/secure_headers/middleware.rb:11:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
 30ae0d9c | /usr/share/foreman/vendor/ruby/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendering common/500.html.erb within layouts/application
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendered common/500.html.erb within layouts/application (Duration: 5.3ms | Allocations: 979)
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendered layouts/_application_content.html.erb (Duration: 7.4ms | Allocations: 5060)
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendering layouts/base.html.erb
2021-06-17T17:55:40 [I|app|30ae0d9c]   Rendered layouts/base.html.erb (Duration: 11.8ms | Allocations: 6025)
2021-06-17T17:55:40 [I|app|30ae0d9c] Completed 500 Internal Server Error in 183ms (Views: 38.8ms | ActiveRecord: 6.4ms | Allocations: 34782)
```

**Comment by keslerm** [comment]
Some screenshots

![image](https://user-images.githubusercontent.com/3018310/122449896-61dd9680-cf74-11eb-8631-50b9525b470f.png)
![image](https://user-images.githubusercontent.com/3018310/122449924-6ace6800-cf74-11eb-8218-6950bdaec8df.png)

**Comment by keslerm** [comment]
![image](https://user-images.githubusercontent.com/3018310/122460775-8a6b8d80-cf80-11eb-9740-26798d159b4f.png)

And then failure while trying to create a host

**Comment by Be-El** [comment]
https://github.com/theforeman/foreman/blob/develop/app/views/compute_resources_vms/show.html.erb#L17

The reason for this error seems to be a missing `@vm` value. If I comment out the breadcrump element for the VM, another downstream error pops up, also indicating that no VM value is present.

**Comment by Be-El** [comment]
The problems seems to be line https://github.com/theforeman/foreman_fog_proxmox/blob/6f0df776794e944a284c5c22200a6955cdcdb45f/app/models/foreman_fog_proxmox/proxmox_vm_queries.rb#L55

The uuid passed in to this method is the id parameter as printed above ("400"). This does not match the parser for the proxmox uuid (<compute_resource_id>_<proxmox vm id>).

Adding `      vmid = uuid if vmid.nil? || vmid.empty?` in the next line fixes this issue and renders the VM details.

**Comment by tristanrobert** [comment]
> ![image](https://user-images.githubusercontent.com/3018310/122460775-8a6b8d80-cf80-11eb-9740-26798d159b4f.png)
> 
> And then failure while trying to create a host

Duplicate with #199
