### ISSUE TITLE
Issues using foreman 3.1.2 and Proxmox 7.1.x

### ISSUE THREAD

**Issue by IncredibleRichie** [theforeman/foreman_fog_proxmox#229]
Hi we use Foreman 3.1.2 and Proxmox 7.1.x and we can not deploy VMs successful.
When i create a VM it gets created right but its not turned on and therefore it can not boot.
Foreman shows an error "can not create vm" and even when i turn the vm on the templates are not rendered due to the error. 

1. Create a vm with foreman 3.1.2 and Proxmox 7.1.x
2. Foreman shows an error

**Expected behavior**
VM should be created successful and foreman shows no error

```
failed to create vm: Task UPID:proxmox:00003BD6:70502DC4:62CEB2F1:qmstart:124:root@pam: failed because start failed: QEMU exited with code 1
2022-07-13T13:56:34 [W|app|f1e1e040] Failed to create a compute Proxmox131 (Proxmox) instance patty-rayne.nr.five: undefined method `identity' for #<Fog::Proxmox::Compute::Real:0x00007fd562c7bbd8>
 f1e1e040 |  
2022-07-13T13:56:34 [I|app|f1e1e040] Backtrace for 'Failed to create a compute Proxmox131 (Proxmox) instance patty-rayne.nr.five: undefined method `identity' for #<Fog::Proxmox::Compute::Real:0x00007fd562c7bbd8>
 f1e1e040 |  ' error (NoMethodError): undefined method `identity' for #<Fog::Proxmox::Compute::Real:0x00007fd562c7bbd8>
 f1e1e040 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/proxmox_vm_commands.rb:53:in `rescue in create_vm'
 f1e1e040 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/proxmox_vm_commands.rb:34:in `create_vm'
 f1e1e040 | /usr/share/foreman/app/models/concerns/orchestration/compute.rb:107:in `setCompute'
```

If you need any other Information please let me know. 

Thank you!

**Comment by Manisha15** [comment]
Does this issue still persist?

**Comment by IncredibleRichie** [comment]
Yes thanks
