### ISSUE TITLE
Issue on Proxmox 7.4-3

### ISSUE THREAD

**Issue by vvinci00** [theforeman/foreman_fog_proxmox#265]
**Describe the bug**
Proxmox v7.4-3 successfully connected but as soon as request "associate VM" got error: no implicit conversion of Integer into String

`Foreman version: 3.6.1
Plugins:
 - foreman-tasks 7.2.1
 - foreman_azure_rm 2.2.9
 - foreman_bootdisk 21.0.4
 - foreman_dhcp_browser 0.0.8
 - foreman_discovery 22.0.4
 - foreman_expire_hosts 8.1.0
 - foreman_fog_proxmox 0.14.0
 - foreman_kubevirt 0.1.9
 - foreman_openscap 6.0.0
 - foreman_puppet 5.1.2
 - foreman_remote_execution 9.1.0
 - foreman_setup 8.0.1
 - foreman_snapshot_management 2.0.3
 - foreman_templates 9.3.0
 - foreman_vault 1.2.0
 - katello 4.8.0

2023-05-22T18:57:27 [I|app|e936bc17] Started PUT "/compute_resources/1-P0/associate?compute_resource_id=1-P0" for 172.20.41.250 at 2023-05-22 18:57:27 +0200
2023-05-22T18:57:27 [I|app|e936bc17] Processing by ComputeResourcesController#associate as HTML
2023-05-22T18:57:27 [I|app|e936bc17]   Parameters: {"authenticity_token"=>"[FILTERED]", "compute_resource_id"=>"1-P0", "id"=>"1-P0"}
2023-05-22T18:57:39 [W|app|e936bc17] no implicit conversion of Integer into String
2023-05-22T18:57:39 [I|app|e936bc17] Backtrace for 'no implicit conversion of Integer into String' error (TypeError): no implicit conversion of Integer into String
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/concerns/host_ext/proxmox/for_vm.rb:27:in `+'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/concerns/host_ext/proxmox/for_vm.rb:27:in `for_vm_uuid'
 e936bc17 | /usr/share/foreman/app/models/host.rb:15:in `method_missing'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/services/concerns/foreman_fog_proxmox/compute_resource_host_associator.rb:29:in `block in associate_hosts'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `block in each'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `each'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/models/foreman_fog_proxmox/vms.rb:25:in `each'
 e936bc17 | /usr/share/gems/gems/foreman_fog_proxmox-0.14.0/app/services/concerns/foreman_fog_proxmox/compute_resource_host_associator.rb:28:in `associate_hosts'
 e936bc17 | /usr/share/foreman/app/controllers/compute_resources_controller.rb:52:in `associate'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:228:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 e936bc17 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 e936bc17 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 e936bc17 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 e936bc17 | /usr/share/gems/gems/audited-5.3.1/lib/audited/sweeper.rb:16:in `around'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 e936bc17 | /usr/share/gems/gems/audited-5.3.1/lib/audited/sweeper.rb:16:in `around'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 e936bc17 | /usr/share/gems/gems/activerecord-6.1.7.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:165:in `process'
 e936bc17 | /usr/share/gems/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:39:in `process'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal.rb:190:in `dispatch'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_controller/metal.rb:254:in `dispatch'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:32:in `each'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:32:in `serve'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:842:in `call'
 e936bc17 | /usr/share/gems/gems/katello-4.8.0/lib/katello/middleware/organization_created_enforcer.rb:18:in `call'
 e936bc17 | /usr/share/gems/gems/katello-4.8.0/lib/katello/middleware/event_daemon.rb:10:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/apipie-dsl-2.5.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 e936bc17 | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/static_dispatcher.rb:68:in `call'
 e936bc17 | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/extractor/recorder.rb:137:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/static.rb:24:in `call'
 e936bc17 | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 e936bc17 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 e936bc17 | /usr/share/gems/gems/apipie-rails-0.8.2/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/tempfile_reaper.rb:15:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/etag.rb:27:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/conditional_get.rb:40:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/head.rb:12:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 e936bc17 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:266:in `context'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:260:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/cookies.rb:697:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 e936bc17 | /usr/share/gems/gems/railties-6.1.7.3/lib/rails/rack/logger.rb:37:in `call_app'
 e936bc17 | /usr/share/gems/gems/railties-6.1.7.3/lib/rails/rack/logger.rb:28:in `call'
 e936bc17 | /usr/share/gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 e936bc17 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 e936bc17 | /usr/share/gems/gems/katello-4.8.0/lib/katello/prevent_json_parsing.rb:12:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/method_override.rb:24:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/runtime.rb:22:in `call'
 e936bc17 | /usr/share/gems/gems/activesupport-6.1.7.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/sendfile.rb:110:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 e936bc17 | /usr/share/gems/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 e936bc17 | /usr/share/gems/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'
 e936bc17 | /usr/share/gems/gems/railties-6.1.7.3/lib/rails/engine.rb:539:in `call'
 e936bc17 | /usr/share/gems/gems/railties-6.1.7.3/lib/rails/railtie.rb:207:in `public_send'
 e936bc17 | /usr/share/gems/gems/railties-6.1.7.3/lib/rails/railtie.rb:207:in `method_missing'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/urlmap.rb:74:in `block in call'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/urlmap.rb:58:in `each'
 e936bc17 | /usr/share/gems/gems/rack-2.2.6.2/lib/rack/urlmap.rb:58:in `call'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
 e936bc17 | /usr/share/gems/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 e936bc17 | /usr/share/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2023-05-22T18:57:39 [I|app|e936bc17]   Rendered common/500.html.erb within layouts/application (Duration: 8.1ms | Allocations: 6908)
2023-05-22T18:57:39 [I|app|e936bc17]   Rendered layouts/base.html.erb (Duration: 9.3ms | Allocations: 9362)
2023-05-22T18:57:39 [I|app|e936bc17]   Rendered layout layouts/application.html.erb (Duration: 25.7ms | Allocations: 28675)
2023-05-22T18:57:39 [I|app|e936bc17] Completed 500 Internal Server Error in 11365ms (Views: 26.6ms | ActiveRecord: 4.8ms | Allocations: 870055)`

**Comment by phantomdez** [comment]
I am getting this issue as well on version 8.x so it's not limited to 7.4.

**Comment by Manisha15** [comment]
> I am getting this issue as well on version 8.x so it's not limited to 7.4.

Which version of the plugin are you using? Is it still throwing error with 0.14.3 version?

**Comment by Manisha15** [comment]
It is fixed with atix-v0.23.0. Please test it again and if it still doesn't work please open another issue with latest proxmox version
