### ISSUE TITLE
undefined method `volumes' for nil:NilClass

### ISSUE THREAD

**Issue by franklin-zamora** [theforeman/foreman_fog_proxmox#266]
**Describe the bug**
Hi, This happens after adding a proxmox 3-node cluster to Foreman.  I can add the cluster, but when I try to add an image, start a VM or create a host, I get that error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Created the connection:
![Screen Shot 2023-06-16 at 3 32 47 pm](https://github.com/theforeman/foreman_fog_proxmox/assets/48812239/7fa5e64d-2e65-4812-b0cc-7b0630f6d361)

2. You can see the nodes in the info screen: 
![Screen Shot 2023-06-16 at 3 32 58 pm](https://github.com/theforeman/foreman_fog_proxmox/assets/48812239/2c94f959-f9ce-427d-a693-cfe3b44ce7fe)

3. I click on "Associate VMs" and get no error.
![Screen Shot 2023-06-16 at 3 33 26 pm](https://github.com/theforeman/foreman_fog_proxmox/assets/48812239/248d583d-f725-4776-b9cc-bc10bd8da3a9)

4. There are no images loaded
![Screen Shot 2023-06-16 at 3 33 35 pm](https://github.com/theforeman/foreman_fog_proxmox/assets/48812239/f1b3e211-99c8-4c1c-b8dd-e82d389c1676)

5. and then when I click on "Create Image"...
![Screen Shot 2023-06-16 at 3 33 43 pm](https://github.com/theforeman/foreman_fog_proxmox/assets/48812239/b52ab676-aeff-4a2a-9852-ea5ebfa3890a)

Also, here are the logs from the Foreman Server:

root@foreman:/home/devenv# foreman-rake errors:fetch_log request_id=43a7ecef
Foreman version: 3.6.1
Plugins:
 - foreman-tasks 7.2.1
 - foreman_ansible 11.2.0
 - foreman_discovery 22.0.4
 - foreman_fog_proxmox 0.14.2
 - foreman_puppet 5.1.2
 - foreman_remote_execution 9.1.0

2023-06-16T15:33:37 [I|app|43a7ecef] Started GET "/compute_resources/3/images/new" for 192.168.1.104 at 2023-06-16 15:33:37 +0930
2023-06-16T15:33:37 [I|app|43a7ecef] Processing by ImagesController#new as HTML
2023-06-16T15:33:37 [I|app|43a7ecef]   Parameters: {"compute_resource_id"=>"3"}
2023-06-16T15:33:37 [I|app|43a7ecef]   Rendered images/new.html.erb within layouts/application (Duration: 196.3ms | Allocations: 7027)
2023-06-16T15:33:37 [I|app|43a7ecef]   Rendered layout layouts/application.html.erb (Duration: 196.7ms | Allocations: 7082)
2023-06-16T15:33:37 [W|app|43a7ecef] undefined method `volumes' for nil:NilClass
2023-06-16T15:33:37 [I|app|43a7ecef] Backtrace for 'undefined method `volumes' for nil:NilClass' error (ActionView::Template::Error): undefined method `volumes' for nil:NilClass
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.2/app/models/foreman_fog_proxmox/proxmox_images.rb:51:in `block in templates'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.2/app/models/foreman_fog_proxmox/proxmox_images.rb:49:in `each'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.2/app/models/foreman_fog_proxmox/proxmox_images.rb:49:in `templates'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.2/app/models/foreman_fog_proxmox/proxmox_images.rb:44:in `available_images'
 43a7ecef | /usr/share/foreman/app/helpers/images_helper.rb:4:in `image_field'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_fog_proxmox-0.14.2/app/views/images/form/_proxmox.html.erb:21:in `_vendor_ruby_______gems_foreman_fog_proxmox________app_views_images_form__proxmox_html_erb___4360369093088258131_149240'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `public_send'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `_run'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:154:in `block in render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:205:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:345:in `instrument_render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:152:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:271:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:53:in `render_partial'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/rendering_helper.rb:45:in `render'
 43a7ecef | /usr/share/foreman/app/views/images/_form.html.erb:7:in `block in _app_views_images__form_html_erb__2296616365444972734_149220'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/capture_helper.rb:45:in `capture'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/form_helper.rb:450:in `form_for'
 43a7ecef | /usr/share/foreman/app/helpers/form_helper.rb:286:in `form_for'
 43a7ecef | /usr/share/foreman/app/views/images/_form.html.erb:1:in `_app_views_images__form_html_erb__2296616365444972734_149220'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `public_send'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `_run'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:154:in `block in render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:205:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:345:in `instrument_render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:152:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/partial_renderer.rb:271:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:22:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/rendering_helper.rb:38:in `block in render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:273:in `in_rendering_context'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/helpers/rendering_helper.rb:34:in `render'
 43a7ecef | /usr/share/foreman/app/views/images/new.html.erb:3:in `_app_views_images_new_html_erb__3786888505486823931_149200'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `public_send'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:247:in `_run'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:154:in `block in render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:205:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:345:in `instrument_render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/template.rb:152:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:117:in `block in _render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/base.rb:273:in `in_rendering_context'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:116:in `_render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/streaming.rb:218:in `_render_template'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:103:in `render_to_body'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/abstract_controller/rendering.rb:25:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/rendering.rb:36:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
 43a7ecef | /usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:45:in `render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:228:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.7.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:165:in `process'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:39:in `process'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal.rb:190:in `dispatch'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_controller/metal.rb:254:in `dispatch'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:32:in `each'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/journey/router.rb:32:in `serve'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/routing/route_set.rb:842:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-dsl-2.5.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.8.2/lib/apipie/static_dispatcher.rb:68:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.8.2/lib/apipie/extractor/recorder.rb:137:in `call'
 43a7ecef | /usr/share/foreman/lib/foreman/middleware/libvirt_connection_cleaner.rb:9:in `call'
 43a7ecef | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/apipie-rails-0.8.2/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/tempfile_reaper.rb:15:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/etag.rb:27:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/conditional_get.rb:27:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 43a7ecef | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:266:in `context'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:260:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/cookies.rb:697:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.1.7.3/lib/rails/rack/logger.rb:37:in `call_app'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.1.7.3/lib/rails/rack/logger.rb:28:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 43a7ecef | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/method_override.rb:24:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/runtime.rb:22:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/activesupport-6.1.7.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/sendfile.rb:110:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/ssl.rb:77:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/actionpack-6.1.7.3/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/secure_headers-6.5.0/lib/secure_headers/middleware.rb:11:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.1.7.3/lib/rails/engine.rb:539:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.1.7.3/lib/rails/railtie.rb:207:in `public_send'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/railties-6.1.7.3/lib/rails/railtie.rb:207:in `method_missing'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/urlmap.rb:74:in `block in call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `each'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 43a7ecef | /usr/share/foreman/vendor/ruby/2.7.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2023-06-16T15:33:37 [I|app|43a7ecef]   Rendered common/500.html.erb within layouts/application (Duration: 3.7ms | Allocations: 753)
2023-06-16T15:33:37 [I|app|43a7ecef]   Rendered layouts/base.html.erb (Duration: 6.7ms | Allocations: 1988)
2023-06-16T15:33:37 [I|app|43a7ecef]   Rendered layout layouts/application.html.erb (Duration: 12.2ms | Allocations: 3003)
2023-06-16T15:33:37 [I|app|43a7ecef] Completed 500 Internal Server Error in 247ms (Views: 13.5ms | ActiveRecord: 8.0ms | Allocations: 14116)

**Comment by Manisha15** [comment]
There is new version of the plugin which should fix the issue. Can you please test if it is working now?
