### ISSUE TITLE
LXC not working

### ISSUE THREAD

**Issue by TNAJanssen** [theforeman/foreman_fog_proxmox#386]
**Describe the bug**
When selecting LXC everything is empty and there is a console error.

**To Reproduce**
1. Go to 'Create Host'
2. Click on 'Virtual Machine'
3. Select 'Type' as 'LXC Container'

**Expected behavior**
See the fields for LXC

**Screenshots**
<img width="526" alt="image" src="https://github.com/user-attachments/assets/00858bfb-e18a-429d-b990-6284bc31f685">

**Desktop (please complete the following information):**
 - Device: Macbook Pro
 - OS: MacOS 15.1
 - Browser ARC
 - Version 1.67.2

**Additional context**
TypeError: Cannot read properties of undefined (reading 'volumes')
    at t.imagesByStorage (ProxmoxStoragesUtils.js:38:60)
    at b (ProxmoxContainerOptions.js:11:22)
    at Ka (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:58067)
    at hl (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:104306)
    at sc (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:96854)
    at lc (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:96779)
    at Jl (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:93809)
    at foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:45451
    at t.unstable_runWithPriority (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:326:3844)
    at Ho (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:45160)
overrideMethod @ hook.js:608
el @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
n.callback @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
pa @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
al @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
fc @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
t.unstable_runWithPriority @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:326
Ho @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
pc @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Jl @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
(anonymous) @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
t.unstable_runWithPriority @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:326
Ho @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Go @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Uo @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
(anonymous) @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
A @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
D @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
F @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Qt @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Xt @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
t.unstable_runWithPriority @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:326
Ho @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
E @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Zt @ foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282
Show 1 more frame
Show less
foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282 Uncaught TypeError: Cannot read properties of undefined (reading 'volumes')
    at t.imagesByStorage (ProxmoxStoragesUtils.js:38:60)
    at b (ProxmoxContainerOptions.js:11:22)
    at Ka (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:58067)
    at hl (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:104306)
    at sc (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:96854)
    at lc (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:96779)
    at Jl (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:93809)
    at foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:45451
    at t.unstable_runWithPriority (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:326:3844)
    at Ho (foreman-vendor.bundle-v13.1.0-production-9a8b6112b9357e54c4f3.js:282:45160)

**Comment by Manisha15** [comment]
Hey @TNAJanssen, May I know which foreman, foreman_fog_proxmox and fog-proxmox version are you using because I can create the LXC host and am not able to reproduce this issue.

**Comment by sasskinn12** [comment]
i have exact same issue with Foreman Version 3.17.0 and ruby-foreman-fog-proxmox  0.19.1-2 (Ubuntu 22.04). Maybe it is related to https://github.com/theforeman/foreman_fog_proxmox/pull/359

Applied the patch, but seems like foreman does not take it into account after restart. how to apply it to test?
https://github.com/theforeman/foreman_fog_proxmox/pull/359/commits/dedf741a1a62398d0d7f770bf30de7bc1e9e383f
