### ISSUE TITLE
Foreman 1.22 - Error 500 when editing existing host.

### ISSUE THREAD

**Issue by LaurentDumont** [theforeman/foreman_fog_proxmox#92]
**Describe the bug**
500 Error when editing an existing host.
Host can be created without any issues.

**To Reproduce**
1. Edit an existing host.

**Versions**
Foreman : 1.22
Foreman Fog Proxmox : 0.8.0
Proxmox : 5.4-6

```
2019-07-11T18:40:50 [I|app|9bcc480b] Processing by HostsController#update as */*
2019-07-11T18:40:50 [I|app|9bcc480b]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"iQ7EugYmBVtLmEeBgBura9CwaIF9o/cT2M0t9LTWhYIbICkOZAXCzS9EVCTLqNSgaRvPSLk59MVb8La3K7iFOw==", "host"=>{"name"=>"docker01", "hostgroup_id"=>"2", "environment_id"=>"1", "puppet_proxy_id"=>"1", "puppet_ca_proxy_id"=>"1", "puppetclass_ids"=>[""], "managed"=>"true", "progress_report_id"=>"[FILTERED]", "interfaces_attributes"=>{"0"=>{"_destroy"=>"0", "mac"=>"c0:ff:ee:00:00:54", "identifier"=>"", "name"=>"docker01", "domain_id"=>"1", "subnet_id"=>"2", "ip"=>"10.10.99.54", "ip6"=>"", "managed"=>"1", "primary"=>"1", "provision"=>"1", "tag"=>"", "attached_to"=>"", "id"=>"191"}}, "architecture_id"=>"1", "operatingsystem_id"=>"2", "medium_id"=>"2", "ptable_id"=>"93", "pxe_loader"=>"PXELinux BIOS", "disk"=>"", "is_owned_by"=>"4-Users", "enabled"=>"1", "model_id"=>"", "comment"=>"Server for CMaker", "overwrite"=>"false"}, "id"=>"76"}
2019-07-11T18:40:50 [I|app|9bcc480b] Current user set to admin (admin)
2019-07-11T18:40:50 [W|app|9bcc480b] Action failed
 | NoMethodError: undefined method `[]=' for nil:NilClass
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_fog_proxmox-0.8.0/app/models/concerns/host_ext/proxmox/interfaces.rb:27:in `add_interfaces_to_compute_attributes'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_fog_proxmox-0.8.0/app/models/concerns/host_ext/proxmox/interfaces.rb:23:in `update'
 | /usr/share/foreman/app/controllers/hosts_controller.rb:116:in `block in update'
 | /usr/share/foreman/app/models/taxonomy.rb:71:in `block in no_taxonomy_scope'
 | /usr/share/foreman/app/models/taxonomy.rb:78:in `block (2 levels) in as_taxonomy'
 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:183:in `as_location'
 | /usr/share/foreman/app/models/taxonomy.rb:77:in `block in as_taxonomy'
 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:146:in `as_org'
 | /usr/share/foreman/app/models/taxonomy.rb:76:in `as_taxonomy'
 | /usr/share/foreman/app/models/taxonomy.rb:70:in `no_taxonomy_scope'
 | /usr/share/foreman/app/controllers/hosts_controller.rb:113:in `update'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
```

![image](https://user-images.githubusercontent.com/8936473/61090694-7ff7ff00-a40d-11e9-81f4-97bc3998cc7a.png)

**Comment by mfuhrmann** [comment]
I run into the same issue. Does removing the fog package solve the issue?

**Comment by mfuhrmann** [comment]
I just found out, that it works. Just remove the package:
`apt remove ruby-foreman-fog-proxmox` and restart foreman/apache2.
